#ifndef CONSTANTS_H
#define CONSTANTS_H

#define OTR_VERSION 4
#define OTR_IDENTITY_MSG_TYPE 0x08
#define OTR_AUTH_R_MSG_TYPE 0x91
#define OTR_AUTH_I_MSG_TYPE 0x88

#define OTR_PRE_KEY_MSG_TYPE 0x0F

#define OTR_DATA_MSG_TYPE 0x03

#endif
